const ProjectData = [
  {
    name: "Online Fast Food Site",
    about: "Site based on popular series Breaking Bad and Better Call Saul",
    details: [
      "API fetching",
      "Redux",
      "Add remove items in cart",
      "Routing",
      "Conditional fetching",
      "Dummy backend",
      "Module CSS",
    ],
    pictureUrl: require("./Images/shopsite.png"),
    siteUrl: "https://serene-lollipop-074fbe.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/losPollosHermanos",
  },
  {
    name: "Movie Base",
    about: "Search unlimited movies and tv shows or view them by categories",
    details: [
      "Responsive",
      "API fetching",
      "Routing",
      "Conditional fetching",
      "Module CSS",
    ],
    pictureUrl: require("./Images/movieSite.png"),
    siteUrl: "https://funny-profiterole-e20648.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/mdtbSite",
  },
  {
    name: "Gym Site",
    about:
      "You can check exercises of every body part,how to do them correctly,what to eat for muscle growth.",
    details: ["Responsive", "Authentifiaction Login/Register", "Slider"],
    pictureUrl: require("./Images/sitepick.png"),
    siteUrl: "https://zesty-malabi-2116ea.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/gymSite",
  },
  {
    name: "Productivity Plan",
    about: "Create lists of plans for all seven days of week",
    details: ["Responsive", "Saving data", "Use of  from and state"],
    pictureUrl: require("./Images/productivityPlan.png"),
    siteUrl: "https://heartfelt-youtiao-d6deb3.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/productivityPlanProject",
  },
  {
    name: "BlackJack",
    about: "Well known card game",
    details: ["Responsive", "Animation", "Game logic"],
    pictureUrl: require("./Images/blackjac.png"),
    siteUrl: "https://quiet-quokka-f873bd.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/blackJack",
  },
  {
    name: "Currency Calculator",
    about: "Convert given amount of money from any curreny to any",
    details: ["Responsive", "Fetching currencies", "Exchange logic"],
    pictureUrl: require("./Images/currchanger.png"),
    siteUrl: "https://startling-scone-01642d.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/currencyCalculator",
  },
  {
    name: "SpaceX Missions",
    about: "Gives information about spaceX missions",
    details: ["Responsive", "API fetching", "GraphQL"],
    pictureUrl: require("./Images/spaceX.png"),
    siteUrl: "https://phenomenal-clafoutis-a7e723.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/spacexProject",
  },
  {
    name: "Catch Dice",
    about: "Collect all same dices,track time and roll number",
    details: ["Responsive", "Game logic", "Timer", "Counter"],
    pictureUrl: require("./Images/dice.png"),
    siteUrl: "https://cosmic-moonbeam-2eab24.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/catchDice",
  },
  {
    name: "Quiz Game",
    about: "5 random questions about anything",
    details: [
      "Responsive",
      "API fetching",
      "answer-checking",
      "conditional styling",
    ],
    pictureUrl: require("./Images/quiz.png"),
    siteUrl: "https://tangerine-paletas-ec07d8.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/quizGame",
  },
  {
    name: "Meme Generator",
    about: "Allows to add upper-lower text to random meme image",
    details: ["Responsive", "API fetching", "Inputs"],
    pictureUrl: require("./Images/meme.png"),
    siteUrl: "https://helpful-arithmetic-956806.netlify.app/",
    gitHub: "https://github.com/DimitriKobakhidze/memeGenerator",
  },
];

export default ProjectData;
